### ISSUE TITLE
Is this only a subscriber or can it also publish as well.  Meaning can I use this in the backend to publisher?

### ISSUE THREAD

**Issue by ebredy** [zyzo/meteor-ddp-php#5]
Is this only a subscriber or can it also publish as well.  Meaning can I use this in the back end to publish and meteor.js on the front end?  Please advise.  Thanks.

**Comment by zyzo** [comment]
@ebredy this is supposed to be used on client side. It does not contain meteor server functions like  `methods()` or `publish()`. Glad to help :) !
